language: cpp
sudo: required
dist: trusty
services: docker
os: linux

# notifications in riot.im
notifications:
  webhooks:
      urls:
          - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFBzaXJ1cyUzQW1hdHJpeC5vcmcvJTIxZG9KWEFCclp5VVBlV0Jmb0ZYJTNBbWF0cml4Lm9yZw"
      on_success: change  # always|never|change
      on_failure: always
      on_start: never

env:
  global:
    - COVERAGE=FALSE
    - BUILD_DIR="$TRAVIS_BUILD_DIR/build"
    - CMAKE_FLAGS="-DENABLE_OPENMP=TRUE -DENABLE_COVERAGE=FALSE EXAMPLES=TRUE -DENABLE_METAMODEL=TRUE -DENABLE_OPTIMIZE=TRUE -DENABLE_ARPACK=TRUE -DENABLE_GEOMETRYCONCRETE=TRUE -DENABLE_MPI=TRUE"

jobs:
  include:
      # unit test stage
    - stage: unittest
      compiler: g++-6
      env: CI_TARGET=unit CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS"
    - compiler: g++-6
      env: CI_TARGET=unit CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug $CMAKE_FLAGS"
    - compiler: clang++
      env: CI_TARGET=unit CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS"
    - compiler: clang++
      env: CI_TARGET=unit CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug $CMAKE_FLAGS"
      # integration tests & examples
    #- stage: build
    - compiler: g++-6
      env: CI_TARGET=test CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS"
    - compiler: g++-6
      env: CI_TARGET=test CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug $CMAKE_FLAGS"
    - compiler: clang++
      env: CI_TARGET=test CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Release $CMAKE_FLAGS"
    - compiler: clang++
      env: CI_TARGET=test CMAKE_FLAGS="-DCMAKE_BUILD_TYPE=Debug $CMAKE_FLAGS -DENABLE_COVERAGE=TRUE" COVERAGE=TRUE
      # lint stage
    #- stage: lint
    - env: CI_TARGET=lint
  allow_failures:
    - env: CI_TARGET=lint
  fast_finish: true

install: ci/install.sh

before_script: ci/before_script.sh

script: ci/script.sh

after_success:
    - cd ..
    - ./scripts/upload_coverage.sh


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-4.0
    packages:
      - build-essential
      - clang
      - g++-6
