language: cpp
sudo: required

services:
    - docker

dist: trusty

compiler:
    - clang
env:
    - BUILD_TYPE=Release OPENMP=FALSE COVERAGE=FALSE EXAMPLES=FALSE
matrix:
    exclude:
        - compiler: clang
          env: BUILD_TYPE=Debug   OPENMP=FALSE COVERAGE=FALSE  EXAMPLES=FALSE
before_install:
    - docker pull nuto/nuto_docker:v2
    - docker run -itd --name docker_container -v $(pwd):/project nuto/nuto_docker:v2
#   ALTERNATIVE: we could also clone the repo instead of mounting it with -v $(pwd):/project
#   - docker run -itd --name docker_container phuschke/githubcppprojecttemplate:v1
#   - docker exec docker_container git clone https://github.com/phuschke/GithubCppProjectTemplate.git /project
script:
    - docker exec docker_container cmake -H/project -B/build
    #- docker exec docker_container cmake --build /build
    - docker exec docker_container cmake --build /build --target unit -- -j2
    #- docker exec docker_container lcov --directory /docker_container --capture --output-file coverage.info
    #- docker exec docker_container lcov --remove coverage.info '/usr/*' --output-file coverage.info
    #- docker exec docker_container lcov --remove coverage.info 'catch.hpp' --output-file coverage.info

#before_script:
#    - mkdir docker_container
#    - cd docker_container
#    - MODULES="-DENABLE_METAMODEL=TRUE -DENABLE_OPTIMIZE=TRUE -DENABLE_ARPACK=TRUE -DENABLE_GEOMETRYCONCRETE=TRUE -DENABLE_MPI=TRUE"
#    - BUILD_OPTIONS="-DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_OPENMP=$OPENMP -DENABLE_COVERAGE=$COVERAGE -DENABLE_EXAMPLES=$EXAMPLES $MODULES"
#    - CXX=clang++ cmake $BUILD_OPTIONS $OPTIONS ..
#script:
#    - make -j2 unit
